spring.application.name=Cine_V2
spring.datasource.url=jdbc:postgresql://localhost:5432/cine_db
spring.datasource.username=cine_user
spring.datasource.password=cine_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# El secreto se inyecta desde una Variable de Entorno
# Nunca escribas la clave real aqu�
jwt.secret=${JWT_SECRET}

# 2. Tiempo de expiraci�n (1 hora)
jwt.expiration=3600000